[refactor]:

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -21,14 +21,31 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 release_file="$INSTALL_SCRIPT-unx.tar.gz"
+url="$INSTALL_SCRIPT_URL/$release_file"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+echo "* Downloading $TOOL_NAME release $ASDF_INSTALL_VERSION as $release_file..."
+( curl "${curl_opts[@]}" \
+    -o "$ASDF_DOWNLOAD_PATH/$release_file" \
+    -C - "$url"
+) || fail "Could not download $url"
+
+echo "* Validating..."
+( curl "${curl_opts[@]}" \
+    -o "$ASDF_DOWNLOAD_PATH/${release_file}.sha512" \
+    -C - "${url}.sha512"
+) || fail "Could not download $url.sha512"
+
+sha512sum -c "$ASDF_DOWNLOAD_PATH/${release_file}.sha512" || fail "Validation failed"
 
 #  Extract contents of tar.gz file into the download directory
 echo "* Extracting $release_file..."
-tar -xzf "$ASDF_DOWNLOAD_PATH/$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+( tar -xzf "$ASDF_DOWNLOAD_PATH/$release_file" \
+    -C "$ASDF_DOWNLOAD_PATH" \
+    --strip-components=1
+) || fail "Could not extract $release_file"
 
-echo "* Removing Archive..."
+echo "* Cleaning Up..."
 # Remove the tar.gz file since we don't need to keep it
 rm "$ASDF_DOWNLOAD_PATH/$release_file"
+rm "$ASDF_DOWNLOAD_PATH/${release_file}.sha512"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -15,11 +15,41 @@ source "${plugin_dir}/lib/utils.bash"
 
 install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
 
+if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
+    fail "asdf-$TOOL_NAME supports release installs only"
+fi
+
+# if texuserdir is set else:
+TEXUSERDIR="$XDG_CONFIG_HOME/texlive"
+
+mkdir -p "$ASDF_INSTALL_PATH/user/texmf-var"
+echo "* Running Installer..."
+(
+    perl "$ASDF_DOWNLOAD_PATH/$INSTALL_SCRIPT" \
+j    --no-interaction \j
+    -scheme=minimal \
+    -texdir "$ASDF_INSTALL_PATH" \
+    -texmflocal "$ASDF_INSTALL_PATH/texmf-local" \
+    -texmfsysvar "$ASDF_INSTALL_PATH/texmf-var" \
+    -texmfsysconfig "$ASDF_INSTALL_PATH/texmf-config" \
+    -texmfhome "$ASDF_INSTALL_PATH/user" \
+    -texmfvar "$ASDF_INSTALL_PATH/user/texmf-var" \
+    -texmfconfig "$TEXUSERDIR"
+) || (
+    rm -rf "$ASDF_INSTALL_PATH"
+    fail "An error occurred while installing $TOOL_NAME $ASDF_INSTALL_VERSION."
+)
+
 # Now install basic binaries
-
-"$ASDF_INSTALL_PATH/$BIN_DIR/tlmgr" install latex-bin collection-basic
-
-# TODO check key?
+echo "* Installing core packages..."
+"$ASDF_ASDF_INSTALL_PATH/$BIN_DIR/tlmgr" install latex-bin collection-basic
 
 # delete weird bin/../man symlink to directoy
-rm "$ASDF_INSTALL_PATH/$BIN_DIR/man"
+rm "$ASDF_ASDF_INSTALL_PATH/$BIN_DIR/man"
+
+(
+    tool_cmd="$(echo "$TOOL_TEST" | cut -d' ' -f1)"
+    test -x "$ASDF_INSTALL_PATH/$BIN_DIR/$tool_cmd" || fail "Expected $ASDF_INSTALL_PATH/$BIN_DIR/$tool_cmd to be executable."
+)
+
+echo "* $TOOL_NAME $ASDF_INSTALL_VERSION installation was successful!"
